// src/resources/js/services/development/react/app-react/Parts.tsx
type Props = {
  title: string;
  setTitle: React.Dispatch<React.SetStateAction<string>>;

  content: string;
  setContent: React.Dispatch<React.SetStateAction<string>>;
};

export default function Parts({ title, setTitle, content, setContent }: Props) {
  console.log('AppReact/Parts');

  const addText = () => {
    setContent((prev) => prev + "[add text]");
  };

  return (
    <div className="border-2 border-gray-300 p-2">
      <div>MyForm: title</div>

      <input
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        className="app-form-input"
      />

      <div className="mt-2">MyForm: content</div>

      <textarea
        value={content}
        onChange={(e) => setContent(e.target.value)}
        className="app-form-input"
      />

      <div className="mt-5 space-x-2">
        <button className="app-btn-primary" onClick={addText}>
          addText
        </button>
      </div>
    </div>
  );
}

// src/resources/js/services/development/vue/app-vue/Parts.vue
<script setup lang="ts">
console.log("AppVue/Parts");

const title = defineModel<string>("title");
const content = defineModel<string>("content");

const addText = () => {
  content.value += "[add text]";
};
</script>

<template>
  <div class="border-2 border-gray-300 p-2">
    <div>MyForm: title</div>
    <input v-model="title" class="app-form-input" />
    <div class="mt-2">MyForm: content</div>
    <textarea v-model="content" class="app-form-input"></textarea>

    <div class="mt-5 space-x-2">
      <button class="app-btn-primary" @click="addText">addText</button>
    </div>
  </div>
</template>
